# Generated by Django 5.2.4 on 2025-07-26 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.SlugField(help_text="Menu Name", unique=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                help_text="Menu which containt the item",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menu.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="named_url",
            field=models.BooleanField(
                default=False, help_text="Is selected URL named or not"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent of this item",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menu.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(help_text="Title of the item", max_length=255),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                help_text="URL (can be named or absolute)", max_length=255
            ),
        ),
    ]
